package com.example.demo.Models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;

@Entity
public class Produce {
    @Id  //primary key of the produce
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // id is auto-generated by the database
	Long id;
	
	@NotBlank
	String name;
// ensures that the name field cannot be null or empty. 
    public Produce(){
        super();
    }
    // default constructor requied by jpa

    public Produce(@NotBlank String name) {
        this.name = name;
    } // the constructor allows us to create a new produce object while setting the 
    //name field i.e Produce apple = new Produce("Apple");

// Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    

}
